version: '3.4'

services:
  ecis-api:
    image: ecis-api
    container_name: ecis-api
    build:
      context: .
      dockerfile: EcisApi/Dockerfile
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/clever-basis-311916-8596115936d4.json
    expose:
      - "5000"
    ports:
      - "5000:5000"

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    user: root
    environment:
      SA_PASSWORD: "EcisDBSecret2021"
      ACCEPT_EULA: "Y"
    volumes:
      - "/home/ubuntu/mssql:/var/opt/mssql/data"
    ports:
      - "1433"

  proxy:
    container_name: proxy
    build:
      context:  ./configs/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    links:
      - ecis-api
    depends_on:
      - ecis-api
